# Generated by Django 5.0.4 on 2024-04-30 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='address',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='contact',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='dob',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='firstname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='lastname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
