# Generated by Django 5.0.4 on 2024-04-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_candidate_max_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=80)),
                ('subject', models.CharField(default='', max_length=500)),
                ('message', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
