# Generated by Django 5.0.4 on 2024-05-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='fullname',
        ),
    ]
