# Generated by Django 5.0.4 on 2024-05-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_message_contact_comments_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
